### ISSUE TITLE
Allow longhand CSS

### ISSUE THREAD

**Issue by andij** [centrica-engineering/muon#183]
## Outcome

Allow for CSS properties to be defined using longhand.

## Scope

- [x] Include the following rules to `.stylelintrc.json`:

```json
"rules": {
 "declaration-block-no-redundant-longhand-properties": null,
 "declaration-block-no-shorthand-property-overrides": true
}
```

---

Currently, Stylelint enforces any CSS properties that when combined could be written using shorthand will not pass the linting.

It's necessary to be able to define style declarations using longhand when all values are defined with design tokens. If a value (design token) for a property does not exist it will be deleted during the PostCSS compilation.

Having is setup this way allows for a property to be defined entirely by using longhand.
 
The linting error will be shown IF a shorthand declaration is added after the longhand.

This will pass:
```css
&:focus-visible {
 outline-color: red;
 outline-offset: 0;
 outline-style: solid;
 outline-width: 3px;
}
```
 
And this will pass:
```css
&:focus-visible {
 outline: 3px;
 outline-color: red;
 outline-offset: 0;
 outline-style: solid;
}
```
 
This will fail:
```css
&:focus-visible {
 outline-color: red;
 outline-offset: 0;
 outline-style: solid;
 outline: 3px;
}
```

Further commentary: https://github.com/centrica-engineering/muon/pull/137#discussion_r792700045
