### ISSUE TITLE
Calculate values for tokens

### ISSUE THREAD

**Issue by andij** [centrica-engineering/muon#201]
## Outcome

Define an approach to calculating values of spacer and size tokens to then use the calculated value for another purpose.

## Scope

Research, development and discovery on techniques related to calculating values of tokens to create values for other tokens.

## Example

The details component has content that is aligned with the edge of the heading, the heading may or may not have an icon or a toggle icon.

This requires the sum of [padding + icon + gap]. If any of these values change, the alignment will be correct.

![calculate](https://user-images.githubusercontent.com/28779/152187771-3f9947f3-0304-4012-be78-f8824a00ad16.png)

This is currently achieved by using `calc()` within the value of the token and calculating these other tokens to supply the value.

Using these tokens:

```js
DETAIL_HEADING_PADDING_INLINE = "1rem";
DETAIL_TOGGLE_ICON_SIZE = "1.5rem";
DETAIL_HEADING_GAP = "1rem";
```

And this technique:

```json
"icon": {
  "spacer": {
    "value": "calc({ detail.heading.padding.inline.value } + { detail.toggle.icon.size.value } + { detail.heading.gap.value })"
  }
}
```

This token is produced:

```js
DETAIL_CONTENT_ICON_SPACER = "calc(1rem + 1.5rem + 1rem)";
```

Then it's used as a value in the CSS to provide the spacing for the `.content` in the details component:

```css
& .has-icon,
& .toggle-start {
  & .content {
    padding-inline-start: $DETAIL_CONTENT_ICON_SPACER;
  }
}
```

The result of the PostCSS build step produces this:

```css
:host .has-icon .content, :host .toggle-start .content {
    padding-inline-start: 3.5rem;
}
```
